export const EVENTS = {
  USER_CONNECT: 'USER_CONNECT',
  USER_DISCONNECT: 'USER_DISCONNECT',
  SEND_MESSAGE: 'SEND_MESSAGE',
  PING: 'PING',
  PONG: 'PONG',
  START_TYPING: 'START_TYPING',
  END_TYPING: 'END_TYPING',
  NEW_USER: 'NEW-USER'
}
