export const EVENTS = {
  USER_CONNECT: 'USER_CONNECT',
  USER_DISCONNECT: 'USER_DISCONNECT',
  SEND_MESSAGE: 'SEND_MESSAGE',
  ALERT_OTHER_USERS: 'ALERT_OTHER_USERS',
  USERS_ALERT_ME: 'ALERT_OTHER_USERS',
  START_TYPING: 'START_TYPING',
  END_TYPING: 'END_TYPING',
  NEW_USER: 'NEW-USER'
}
